apiVersion: v1
kind: Service
metadata:
  name: automation-servicenew
  namespace: default
spec:
  selector:
     app: automation-api
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer