apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.releaseName}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.releaseName}} 
  template:
    metadata:
      labels:
        app: {{.Values.releaseName}}
    spec:
      containers:
      - image: phico/frontend:1.1
        imagePullPolicy: Always
        name: frontend
        ports:
        - name: frontend
          containerPort: 4200

