apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{.Values.releaseName}}
  name: {{.Values.releaseName}}
spec:
  clusterIP: None  
  ports:
    - protocol: "TCP"
      port: {{.Values.servicePort}}
      targetPort: 8080
  selector:
    app: {{.Values.releaseName}}
